### ISSUE TITLE
Need option to sort report by day rather than issue

### ISSUE THREAD

**Issue by StevenKW** [ajthenewguy/worklog#4]
Would be helpful to have a report sorted by day.
![image](https://cloud.githubusercontent.com/assets/4203807/24913641/9b461efe-1e86-11e7-9d8e-93165dd195b3.png)

**Comment by fissible** [comment]
Implemented, use `-g date`
By default it is now grouping by date, so the flag is only needed if you want to group by issue like the "today" variant.
