### ISSUE TITLE
worklog start should start at current time if there is no current task.

### ISSUE THREAD

**Issue by StevenKW** [ajthenewguy/worklog#6]
Let's say I start work in the morning
wlog start @ 7a
wlog stop @ noon

wlog start @ 1pm (this entry should start at 1pm not back into noon)

**Comment by fissible** [comment]
Fixed with commit https://github.com/ajthenewguy/worklog/commit/1338c5b18431a78ed06a0c21255a903dc23e8db0
The "window" is 10 minutes. If you start a new task and the last one was <= 10 minutes ago, it will use the last task stop time as the start.
