### ISSUE TITLE
Worklog report alignment

### ISSUE THREAD

**Issue by StevenKW** [ajthenewguy/worklog#7]
Align issues right and align descriptions left.
Current on left / Suggested on right
![image](https://cloud.githubusercontent.com/assets/4203807/25443803/ca89ca52-2a5d-11e7-853e-d1381763449e.png)

**Comment by fissible** [comment]
Implemented in https://github.com/ajthenewguy/worklog/commit/ddf06c54d753ce524c296869004e947541a878f3
